### ISSUE TITLE
 Standard Output Handle for this console

### ISSUE THREAD

**Issue by davebush** [MicrosoftDocs/Console-Docs#148]
It is worth noting that if a process does not have a console before calling this, then function `GetStdHandle(STD_OUTPUT_HANDLE)` will not have returned a valid handle that will then write to this console.

This is often done during startup by code environments - e.g. the Console stream in Dot Net.

To gurantee a valid handle to write to this console you have to call `GetStdHandle(STD_OUTPUT_HANDLE)` _after_ calling it. (And then use the returned handle.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d59483-7cf9-300f-de81-d316509279c2
* Version Independent ID: f0a47b91-e864-8832-5ba3-5fb6400ba8b7
* Content: [AttachConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/attachconsole)
* Content Source: [docs/attachconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/attachconsole.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
As far as I can tell, this document didn't specifically get into that because console mode applications (with the bit flag set in the PE header by choosing `/SUBSYSTEM:CONSOLE` in the linker or a VS project type that sets that...) are allocated a console on startup before the main method is entered and have a console handle returned on that method from the get-go. Being a non-console application (`/SUBSYSTEM:WINDOWS`) going after those handles is a little further off the rails and I think the document considered it well understood that if you need a console.... then declaring yourself a console application or allocating yourself one with this method was a sensible thing to do prior to attempting to use it.

However, I can clarify on this page in the remarks section to that effect.

**Comment by miniksa** [comment]
I've pushed a proposed commit of changes that adds clarification to both the `AttachConsole` and `GetStdHandle` pages to hopefully make this easier to understand. It should be linked here.
