### ISSUE TITLE
Unclear when WriteConsoleOutput uses unicode

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/Console-Docs#149]
> This function uses either Unicode characters or 8-bit characters from the console's current code page.
This is nice, but it doesn't actually specify how the function decides which to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5911fa-1f51-7d18-c83e-9c132523e613
* Version Independent ID: b761d759-de53-a0d2-cfbc-48c9c8cf4e99
* Content: [WriteConsoleOutput function - Windows Console](https://docs.microsoft.com/en-us/windows/console/writeconsoleoutput)
* Content Source: [docs/writeconsoleoutput.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/writeconsoleoutput.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by DHowett** [comment]
This is like all other APIs that are split into `A` and `W` variants: It uses the ANSI codepoints from the codepage when you use the `A` variant (`WriteConsoleOutputA`) and Unicode characters when you use the `W` variant (`WriteConsoleOutputW`). This was not documented here because it would be redundant with all other windows documentation on the `A` vs `W` APIs.
