### ISSUE TITLE
No listing of error codes for SetConsoleCursorPosition

### ISSUE THREAD

**Issue by Lucretiel** [MicrosoftDocs/Console-Docs#157]
I'm currently trying to debug an FFI issue related to SetConsoleCursorPosition returning a certain error. However, it doesn't appear to be documented what possible errors can be returned from SetConsoleCursorPosition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ffd9dd3-6817-3c0e-e828-3e07cab63256
* Version Independent ID: bbbfe14b-18b1-2b55-54a0-d6d0f822e13d
* Content: [SetConsoleCursorPosition function - Windows Console](https://docs.microsoft.com/en-us/windows/console/setconsolecursorposition)
* Content Source: [docs/setconsolecursorposition.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/setconsolecursorposition.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
The only errors I can see coming out of that function are `E_INVALIDARG` (`0x80070057`), `STATUS_INVALID_PARAMETER` (`0xC000000D`) or some HRESULTification of the NTSTATUS through the `HRESULT_FROM_NT` macro like `HRESULT_FROM_NT(STATUS_INVALID_PARAMETER)` which is (`0xD000000D`). 

Are you seeing any other error than that?

We generally haven't documented the specific errors out of these APIs because tracing the comprehensive set of errors from all APIs is virtually impossible.

Also do note that you can see a lot of the logic behind these APIs by looking inside `conhost.exe`'s code now that it's open source at: https://github.com/microsoft/terminal/tree/main/src/host

**Comment by Lucretiel** [comment]
STATUS_INVALID_PARAMETER is what we were seeing, no issues there. This came up in https://github.com/kkawakam/rustyline/pull/434 (which in turn was triggered by https://github.com/nushell/nushell/issues/2440), where this call was causing the error in some terminals (Windows Terminal, Alacritty) but not others (cmd), and seemingly it shouldn't be happening at all. We couldn't figure out from the docs what specifically might cause this error to occur in a case where the inputs are correct.

**Comment by miniksa** [comment]
The only way I could tell you which parameter was at fault or why would be to have a complete debugger state attached to the `conhost.exe` involved. Sorry. 

If you're using Windows Terminal, though, it will have `openconsole.exe` powering the session (which is an open version of `conhost.exe`) and should have symbols and source available by nature of being built from our GitHub. That would perhaps help you all see what's going on.

Do you mind if I close this issue then? I don't think I can document my way to success on this one.

**Comment by Lucretiel** [comment]
No problem
