### ISSUE TITLE
Spelling Errors in PrintUI.dll

### ISSUE THREAD

**Issue by mubix** [MicrosoftDocs/Console-Docs#206]
I have no idea which repository this should go into as an issue, but I thought I would bring up two spelling errors in the output of `PrintUI.dll`

First is `skipping`:
```diff
-  /im install printer using add printer wizard skiping network listed printers
+  /im install printer using add printer wizard skipping network listed printers
```

And the second is `existing`:
```diff
-   /R force selected driver to replace exisiting driver
+   /R force selected driver to replace existing driver

```

**Comment by miniksa** [comment]
I'm feelin' pretty good on this Friday so I filed MSFT:35292109 internally for you, found the ownership team and their branch, made a PR to fix this, and sent it at them with the information. Thank you for the report. It should be fixed in a future edition of Windows. It wasn't the right place, but it looks like it'll work out anyway. :)

**Comment by miniksa** [comment]
This has merged to Windows today. Which build it will appear in is beyond me at this point, but thanks for your report!
