### ISSUE TITLE
Wincon.h or ConsoleApi.h

### ISSUE THREAD

**Issue by gvanem** [MicrosoftDocs/Console-Docs#40]
Why does the doc say `Header: Wincon.h (include Windows.h)` when the prototype is in fact in `consoleapi.h`? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600cb1d1-7698-f4e8-2775-b1b7acc2c0f0
* Version Independent ID: 15c3bf4f-0aa1-9ecc-1288-a225cf13958f
* Content: [CreatePseudoConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole)
* Content Source: [docs/createpseudoconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/createpseudoconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by zadjii-msft** [comment]
That's almost certainly an oversight. It probably should be corrected to `consoleapi.h`. Curious that the other ones are defined in `wincon.h` and not also `consoleapi.h`... 

@bitcrazed can you come through and fix the PseudoConsole functions?

**Comment by miniksa** [comment]
OK. Why does it say this?

I simply copy/pasted the template from other documentation files when creating this one a few months ago.

So then the question is... why is it technically wrong for almost all the APIs?

That's because they used to be in wincon.h (which you really shouldn't include yourself and should include windows.h as directed.) But when APIs started getting collected into APIsets, the function declarations were duplicated into consoleapi.h/consoleapi2.h/consoleapi3.h. About a release or two ago, I de-duplicated these by removing them from wincon.h and pointing at the individual set headers. However, also at the same time, we were changing documentation systems to docs.microsoft.com and I probably was unable to update the docs at the exact time I made the change because all docs were in flux. Then I promptly forgot about it.

So what I'm going to do is walk through all the APIs and update which header they're actually in, but still leave the directive that you really ought to just get them by nature of including windows.h, not the individual files.

**Comment by gvanem** [comment]
The MS-SDK docs is a real mess and in a flux. E.g. when Googling for `_mm_store_si128 site:microsoft.com`, all top-hit land on  non-English pages! The first [MSDN-hit](https://msdn.microsoft.com/en-us/library/hh977023.aspx), further links to an Intel page. Go figure.

**Comment by miniksa** [comment]
Yep, such is the state of things. I just focus on trying to fix my little corner of the world.
