### ISSUE TITLE
Is default foreground color black or white?

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/Console-Docs#75]
The content says:
"If no background constant is specified, the background is black, and if no foreground constant is specified, the text is black."
But I suspect it might be backwards - is the default foreground/text color actually white, rather than black? (If the default background and foreground were both black, the default text output would be invisible.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f0eb74-9b09-16ab-5894-af4d96361bac
* Version Independent ID: 8eb4eea7-dd66-2bc8-9052-7de8495f26f1
* Content: [Console Screen Buffers - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-screen-buffers)
* Content Source: [docs/console-screen-buffers.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-screen-buffers.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by bitcrazed** [comment]
What you're actually specifying by `OR`-ing these values together is a foreground (low-nybble) and background (high-nybble) index into the current Console's palette. If you specify 0x0000 for the background and 0x0000 for the foreground, then your text will be drawn in black on black because color 0x0 in most Console's palette is black.

Note that the Console API currently offers no support for "default foreground and background colors" as discussed in [the recent blog post announcing this new experimental feature](https://blogs.msdn.microsoft.com/commandline/2018/12/10/new-experimental-console-features/).
