### ISSUE TITLE
Which version of windows is supported?

### ISSUE THREAD

**Issue by Mart-Bogdan** [MicrosoftDocs/Console-Docs#83]
Starting from what windows version are VT sequences supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by zadjii-msft** [comment]
I believe we first added support in 10586 (TH2), and the large majority of our support was added in the Anniversary update, 14393.

**Comment by bitcrazed** [comment]
In addition, its important to note that every Win10 release since TH2 has received many important fixes & improvements to Console's VT implementation, so we do recommend using the most recently released version of Windows in order to experience the best VT support.

And, of course, if you do find issues with our implementation, please file issues in the Console repo: https://github.com/microsoft/console

Closing this issue since there's no further action required.
