### ISSUE TITLE
Use CreateFile() instead of GetStdHandle() in samples

### ISSUE THREAD

**Issue by rivy** [MicrosoftDocs/Console-Docs#93]
`GetStdHandle(STDOUT)` fails when STDOUT is redirected, even if a valid console is available (ie, for STDERR).

Instead, use `CreateFile2("CONOUT$", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_WRITE, OPEN_EXISTING, null)` which will grab a handle to the console even if STDOUT and/or STDERR is redirected.

IMO, it's a better method and should be changed here so that others will use the better version in the wild.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#feedback)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by rivy** [comment]
Alternatively, `CreateFileA()` or `CreateFileW()` could be used, allowing for compatibility back to WinXP.

**Comment by rivy** [comment]
# ⚰️ 

At about five months in without response... I'm closing this as #ignored / #no-interest.

**Comment by miniksa** [comment]
Sorry, I am vaguely interested in documenting using the CreateFile routes VS the standard handle routes. But it hasn't been a major priority relative to things in the Terminal project for me this summer. I know there can be nuances to the handle difference that I would want to look up before documenting it and that I'd probably want to make a new page instead of changing it only here. 

I probably should have said that earlier instead of just leaving this in my long to do list. 

I didn't mean to make you feel like this wasn't important at all. I would still love it open for a someday priority.

**Comment by rivy** [comment]
@miniksa , This has been open for over two years, so, I'm going to close it to get it off my open issue list.

If you're interested in pursuing it, you could open it as a new issue owned by you.

**Comment by miniksa** [comment]
Alright, I'll log it from/for myself.
